backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: sitecontent
    label: Site Content
    files:
      - name: news
        label: News
        file: content/news.json
        format: json
        fields:
          - name: items
            label: News Items
            widget: list
            fields:
              - { name: id, label: ID, widget: string }
              - { name: tag, label: Tag, widget: string, default: "Update" }
              - { name: title, label: Title, widget: string }
              - { name: ts, label: Date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
              - { name: excerpt, label: Summary, widget: text }
      - name: articles
        label: Articles
        file: content/articles.json
        format: json
        fields:
          - name: items
            label: Articles
            widget: list
            fields:
              - { name: id, label: ID, widget: string }
              - { name: title, label: Title, widget: string }
              - { name: author, label: Author, widget: string, default: "Wartime Lebanon Desk" }
              - { name: ts, label: Date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
              - { name: body, label: Body, widget: markdown }
